### PR TITLE
Add DynamoDB storage driver

### PR DESCRIPTION
**Pull request by jkmathes**
A storage plugin to allow storing slack-machine data into AWS DynamoDB

Optional slack-machine settings introduced:

`DYNAMODB_ENDPOINT_URL` - specifies an optional alternate endpoint, for local bot testing
`DYNAMODB_KEY_PREFIX` - an optional prefix to use within the key lookup. Defaults to `SM:`
`DYNAMODB_TABLE_NAME` - specifies the table to use in DynamoDB. Defaults to `slack-machine-state`
`DYNAMODB_CREATE_TABLE` - optionally -create- the table to be used in DynamoDB. Defaults to `False`
`DYNAMODB_CLIENT` - if custom configuration is needed for the DynamoDB client, an optional client can be specified here

### CODE REVIEW

**Comment by DandyDev** [comment]
Looks beautiful! And the timing is great as well. Just moved to a new job that uses AWS as cloud provider. So thanks for this!

**Comment by DandyDev** [comment]
I do have one request: could you document this new storage backend [here](https://github.com/DandyDev/slack-machine/blob/master/docs/user/usage.rst)?

**Comment by jkmathes** [comment]
It should be updated (and now, with the correct formatting!) - thoughts?

**Comment by DonDebonair** [comment]
This was fixed in [v0.27.1](https://github.com/DonDebonair/slack-machine/releases/tag/v0.27.1). It has only been implemented for the upcoming async version of Slack Machine

**Pull request closed without merging**
